apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-master
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-nfs-master  # 显式绑定到指定 PV
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-server1
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-nfs-server1  # 显式绑定到指定 PV
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-server2
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-nfs-server2  # 显式绑定到指定 PV