# fencing-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zkfc-fencer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zkfc-fencer-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zkfc-fencer-binding
subjects:
- kind: ServiceAccount
  name: zkfc-fencer
  namespace: default
roleRef:
  kind: ClusterRole
  name: zkfc-fencer-role
  apiGroup: rbac.authorization.k8s.io
