apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-env
data:
  HADOOP_USER: "hadoop"
  JAVA_HOME: "/opt/java"
  HADOOP_MAPRED_HOME: "/opt/hadoop"
  HADOOP_USER: "hadoop"
  HDFS_NAMENODE_USER: "hadoop"
  HDFS_DATANODE_USER: "hadoop"
  HDFS_SECONDARYNAMENODE_USER: "hadoop"
  YARN_RESOURCEMANAGER_USER: "root"
  YARN_NODEMANAGER_USER: "root"
  MAPRED_HISTORYSERVER_USER: "hadoop"
  HADOOP_OPTS: "-Djava.net.preferIPv4Stack=true -Dhadoop.security.logger=INFO,RFAS -Djava.security.manager=allow"
  HADOOP_LOG_DIR: "/hadoop/logs/hadoop"
  HADOOP_CONF_DIR: "/opt/hadoop/etc/hadoop"
  YARN_LOG_DIR: "/hadoop/logs/yarn"
  HADOOP_HEAPSIZE_MAX: "2048m"
  HADOOP_MAPRED_ROOT_LOGGER: "INFO, CONSOLE"