apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: data
  labels:
    app.kubernetes.io/name: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: hubo-search
    discovery.type: single-node
    network.host: 0.0.0.0
    http.port: 9200
    transport.port: 9300
    xpack.security.enabled: true
    xpack.security.http.ssl.enabled: false
    xpack.security.enrollment.enabled: false
    action.destructive_requires_name: true
    cluster.routing.allocation.disk.watermark.low: "85%"
    cluster.routing.allocation.disk.watermark.high: "90%"
    cluster.routing.allocation.disk.watermark.flood_stage: "95%"
