apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elasticsearch-secret
  namespace: data
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: elasticsearch-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ELASTIC_PASSWORD
      remoteRef:
        key: secret/data/elasticsearch/app
        property: ELASTIC_PASSWORD
