apiVersion: v1
kind: Namespace
metadata:
  name: data
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-rgw
  namespace: data
  labels:
    app.kubernetes.io/name: ceph-rgw
    app.kubernetes.io/component: object-storage
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7480
      targetPort: 7480
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ceph-rgw
  namespace: data
  labels:
    kubernetes.io/service-name: ceph-rgw
    endpointslice.kubernetes.io/managed-by: armbianbegin-ceph-rgw
    app.kubernetes.io/name: ceph-rgw
    app.kubernetes.io/component: object-storage
addressType: IPv4
ports:
  - name: http
    port: 7480
    protocol: TCP
endpoints:
  - addresses:
      - 192.168.137.211
    conditions:
      ready: true
    hostname: orangepi5-max-server1
  - addresses:
      - 192.168.137.201
    conditions:
      ready: true
    hostname: nanopct4-server1
