# ceph-csi-config.yaml — CSI 驱动连接 Ceph 集群的配置
# clusterID 通过 `ceph fsid` 获取
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi-config
  namespace: default
data:
  config.json: |
    [
      {
        "clusterID": "3a4899f0-7689-11f1-90a0-c0742bfe683a",
        "monitors": [
          "192.168.137.101:6789",
          "192.168.137.201:6789",
          "192.168.137.202:6789",
          "192.168.137.203:6789",
          "192.168.137.211:6789"
        ],
        "cephUserName": "k8s",
        "cephUserSecret": "QVFBQ3MwZHFUbkVLTFJBQXZCRDIwMm1WT250RFduWkRiM0RnMnc9PQ=="
      }
    ]
