# ceph-secret.yaml — K8s 连接 Ceph 的认证密钥
# 用法: kubectl create secret generic ceph-secret -n default --from-literal=userID=k8s --from-literal=userKey=$(ceph auth get-key client.k8s)
apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: default
stringData:
  userID: k8s
  userKey: AQACs0dqTnEKLRAAvBD202mVOntDWnZDb3Dg2w==
