# rbd-pvc.yaml — RBD 块存储 PVC 示例
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc
spec:
  accessModes:
    - ReadWriteOnce           # RBD 仅支持单节点读写
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 100Gi
