# hadoop-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  labels:
    app: zookeeper
    component: config
data:
  # ========================
  # 核心配置文件
  # ========================
  zoo.cfg: |
    tickTime=2000
    dataDir=/data
    dataLogDir=/logs
    clientPort=2181
    initLimit=5
    syncLimit=2
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=1
    maxClientCnxns=60
    server.0=zk-0.zk-hs.default.svc.cluster.local:2888:3888
    server.1=zk-1.zk-hs.default.svc.cluster.local:2888:3888
    server.2=zk-2.zk-hs.default.svc.cluster.local:2888:3888
  init-zookeeper.sh: |
    #!/bin/bash
    echo ${ZOO_MY_ID} | awk -F- '{print $2}' > /data/myid
    /opt/zookeeper/bin/zkServer.sh start-foreground
