# /etc/gitea/app.ini（需手动创建）
APP_NAME = MyGitea
RUN_MODE = prod
[repository]
ROOT = /var/lib/gitea/data/repositories
[database]
# DB_TYPE = mysql
# HOST = mysql.gitea.svc.cluster.local:3306
# NAME = gitea
# USER = gitea
# PASSWD = 1234
DB_TYPE  = sqlite3
PATH     = /var/lib/gitea/data/gitea.db
LOG_SQL  = false
[server]
DOMAIN       = gitea.zmh.com
HTTP_PORT    = 3000
ROOT_URL     = http://gitea.zmh.com/
[app]
APP_DATA_PATH = /var/lib/gitea/data
[webhook]
ALLOWED_HOST_LIST = drone.zmh.com,192.168.137.101