apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-env
  namespace: gitops
data:
  DRONE_DATADOG_ENABLED: "false"
  DRONE_GITEA_SERVER: "https://gitea.panghuer.top"
  DRONE_SERVER_HOST: "drone.panghuer.top"
  DRONE_SERVER_PROTO: "https"
  DRONE_SERVER_PORT: ":8080"
  DRONE_LOGS_DEBUG: "false"
  DRONE_WEBHOOK_ALLOW_ALL_HOSTS: "false"
  DRONE_RPC_PROTO: "http"
  DRONE_RPC_HOST: "drone-server.gitops.svc.cluster.local:8080"
  DRONE_RUNNER_NAME: "kube-runner"
  DRONE_RUNNER_CAPACITY: "2"
  DRONE_NAMESPACE_DEFAULT: "drone-builds"
  DRONE_RUNNER_POD_TERMINATION_GRACE_PERIOD: "60"
  DRONE_RUNNER_POD_TTL_AFTER_FINISHED: "5m"
