apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-env
  namespace: gitops
data:
  DRONE_DATADOG_ENABLED: "false"
  # Server 配置
  DRONE_GITEA_SERVER: "http://gitea.zmh.com:30080"
  DRONE_GITEA_CLIENT_ID: "ae06f149-708a-45ad-9b54-2290bd028ba1"
  DRONE_GITEA_CLIENT_SECRET: "gto_vhnq34agjtyyawcaecyvqlwikt7n6d7wgu2b3h43t5bdywktj3ta"
  DRONE_RPC_SECRET: "5298dbe4c42691ca07db4aa9eefba83b"
  DRONE_SERVER_HOST: "http://drone.zmh.com:30080"
  DRONE_SERVER_PORT: ":8080"
  DRONE_HTTP_BIND: ":8080"  # 修正后的端口绑定
  DRONE_SERVER_PROTO: "http"
  DRONE_LOGS_DEBUG: "true"
  DRONE_WEBHOOK_ALLOW_ALL_HOSTS: "true"

  # Runner 配置
  DRONE_RPC_PROTO: "http"
  DRONE_RPC_HOST: "drone.zmh.com:30080"
  DRONE_RUNNER_NAME: "kube-runner"
  DRONE_RUNNER_CAPACITY: "2"
  DRONE_NAMESPACE_DEFAULT: "gitops"

  # 保证被runner创建的pod可以在失败或成功后快速删除
  DRONE_RUNNER_POD_TERMINATION_GRACE_PERIOD: "60"
  DRONE_RUNNER_POD_TTL_AFTER_FINISHED: "5m"