# mysql-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: gitops
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: nanopct4-master:5000/mysql:latest
        envFrom:
        - configMapRef:
            name: gitea-env
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ceph-rbd  # RBD 存储类
      resources:
        requests:
          storage: 10Gi
---
# mysql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: gitops
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306  # 必须与容器监听端口一致