apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agent-secret
  namespace: bingbichunqiu-agent
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: agent-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/data/bingbichunqiu-agent/api
