# hive-metastore-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: default
spec:
  replicas: 1  # 多副本实现高可用
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
      - name: hive-metastore
        image: nanopct4-master:5000/hive_hadoop:latest
        # command: ["/bin/sh", "-c"]
        # args:
        # - |
        #   tail -f /dev/null
        command: ["/bin/sh", "-c"]
        args:
        - |
          # tail -f /dev/null
          # schematool -dbType mysql -initSchema \
          #  --verbose \
          #  -url jdbc:mysql://mysql.default.svc.cluster.local:3306/hive_metastore \
          #  -user root \
          #  -pass 123456
          start-metastore
        env:
        - name: MYSQL_JDBC_URL
          value: "jdbc:mysql://mysql.default.svc.cluster.local:3306/hive_metastore?createDatabaseIfNotExist=true"
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "hive_metastore"
        - name: MYSQL_USER
          value: "hadoop"
        - name: MYSQL_PASSWORD
          value: "1234"
        ports:
        - containerPort: 9083
        readinessProbe:
          tcpSocket:
            port: 9083
          initialDelaySeconds: 30
          periodSeconds: 10
        securityContext:
          runAsUser: 1000  # 直接指定用户 ID（如 hadoop 用户的 UID）
          runAsGroup: 1000 # 直接指定组 ID（如 hadoop 组的 GID）
        volumeMounts:
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/log4j.properties
          subPath: log4j.properties
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/core-site.xml
          subPath: core-site.xml
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/hdfs-site.xml
          subPath: hdfs-datanode-site.xml
        - name: hadoop-config-volume
          mountPath: /opt/hadoop/etc/hadoop/mapred-site.xml
          subPath: mapred-site.xml
        - name: hive-config-volume
          mountPath: /opt/hive/conf/hive-site.xml
          subPath: hive-spark-site.xml
        envFrom:
        - configMapRef:
            name: hadoop-env
      volumes:
      - name: hadoop-config-volume
        configMap:
          name: hadoop-config
          defaultMode: 0755  # 关键权限设置
      - name: hive-config-volume
        configMap:
          name: hive-config
          defaultMode: 0755  # 关键权限设置
---
# hive-metastore-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: default
spec:
  type: NodePort  # 添加此行
  selector:
    app: hive-metastore
  ports:
  - port: 9083
    targetPort: 9083
    nodePort: 30983